"""empty message

Revision ID: 688615437230
Revises: ab9668695114
Create Date: 2024-12-11 01:39:35.524318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688615437230'
down_revision = 'ab9668695114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roupa', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=512, collation='Latin1_General_CI_AS'),
               type_=sa.String(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=512, collation='Latin1_General_CI_AS'),
               nullable=True)

    with op.batch_alter_table('roupa', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
