"""Criar tabelas Usuario e Roupa

Revision ID: ab9668695114
Revises: eb79b0beb3a5
Create Date: 2024-12-11 01:22:41.333996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9668695114'
down_revision = 'eb79b0beb3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roupa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco', sa.Float(), nullable=False))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=512, collation='Latin1_General_CI_AS'),
               type_=sa.String(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=512, collation='Latin1_General_CI_AS'),
               nullable=True)

    with op.batch_alter_table('roupa', schema=None) as batch_op:
        batch_op.drop_column('preco')

    # ### end Alembic commands ###
